export const GET_SCHOOL_ICON_REQUEST = 'GET_SCHOOL_ICON_REQUEST';
export const GET_SCHOOL_ICON_SUCCESS = 'GET_SCHOOL_ICON_SUCCESS';
export const GET_SCHOOL_ICON_FAILURE = 'GET_SCHOOL_ICON_FAILURE';

export const GET_STORAGE_DATA_REQUEST = 'GET_STORAGE_DATA_REQUEST';
export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';

export const APP_USER_PROFILE_REQUEST = 'APP_USER_PROFILE_REQUEST';
export const APP_USER_PROFILE_SUCCESS = 'APP_USER_PROFILE_SUCCESS';
export const APP_USER_PROFILE_FAILURE = 'APP_USER_PROFILE_FAILURE';

export const SHOW_LOADING_GIF = 'SHOW_LOADING_GIF';
export const CLOSE_LOADING_GIF = 'CLOSE_LOADING_GIF';
